apiVersion: v1
kind: Secret
metadata:
  name: {{ template "inventory-service.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "inventory-service.name" . }}
    chart: {{ template "inventory-service.chart" .  }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  RDS_PASSWORD: {{ .Values.rds.password | b64enc | quote }}