apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "postgres.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
data:
{{ .Values.postgres.configuration | indent 4 }}
