apiVersion: v1
kind: Secret
metadata:
  name: {{ template "postgres.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "postgres.name" . }}
    chart: {{ template "postgres.chart" .  }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.postgrescred.password | b64enc | quote }}