apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      nodePort: 30672
      name: amqp
    - port: {{ .Values.service.managerPort }}
      targetPort: {{ .Values.service.managerPort }}
      protocol: TCP
      nodePort: 31672
      name: http
  selector:
      app: {{ template "rabbitmq.name" . }}
      release: "{{ .Release.Name }}"
